Сервис рекомендаций
c0m14/java-filmorate pull request #12
Opened 2023-05-28 18:12 UTC by Vexvl

Добавлен сервис рекомендаций, методы в него. Также добавлены методы для работы с бд в FilmRepository, один тест в FilmTest shouldFillSeveralUserLikes

2023-05-28 18:25 UTC, Vexvl commented on src/test/java/ru/yandex/practicum/filmorate/FilmTest.java
> +        assertEquals(initialFilm.getMpa().getId(), savedFilm.getMpa().getId(), "Incorrect field mpa in saved film");
тут было немного опечаток

2023-05-29 09:20 UTC, c0m14 requested changes
Привет! 
сорри, немного почелленджил основную логику по которой рекомендации сейчас достаются - посмотри, может больше понравится одним запросов вытаскивать сразу?

2023-05-29 09:20 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/service/recommendations/RecommendationsService.java
> +    }
Заранее сорри за занудство :)
Мне кажется немного не эффективно каждый раз при запросе рекомендации вытаскивать по сути всю таблицу лайков - как вариант вытащить сразу рекомендованные фильмы вот таким запросом (для упрощения запроса использовал оконные функции, про них Аня кидала статью в прошлом спринте)

тут сразу ограничиваем обзор текущим юзером

WITH
commonFilms(film_id) AS (
	SELECT film_id FROM USER_FILM_LIKES
	WHERE user_id = :userId
),
similiarUsers(user_id) AS (
	SELECT user_id FROM USER_FILM_LIKES
	WHERE film_id IN (SELECT film_id FROM commonFilms)
)

SELECT film_id FROM USER_FILM_LIKES 
WHERE user_id IN (SELECT user_id FROM similiarUsers)
AND film_id NOT IN (SELECT film_id FROM commonFilms); --отсекаем фильмы, которые уже лайкнул пользователь

2023-05-29 09:21 UTC, Yuri-Yamaltdinov requested changes
Привет! Интересная получилась функциональность)
Оставил несколько комментариев, кое-что нужно подкорректровать и пару вопросов.

2023-05-29 09:21 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmStorage.java
> +    Map<Long, Set<Long>> fillInUserLikes();
Почему мапа не final? ссылка может меняться на другую мапу?

2023-05-29 09:21 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +    private final JdbcTemplate jdbcTemplateNotNamedParameter;
Почему выбрал такое наименование как jdbcTemplateNotNamedParameter? Чтобы отличалось от используемого в базовом проекте NamedParameter?
Если нет конфликта с наименованием jdbcTemplate - предлагаю использовать так, чтобы не усложнять читаемость кода.

2023-05-29 09:21 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +        String sqlQuery = "SELECT uf.USER_ID, uf.FILM_ID " +
Объединяешь две таблицы, а делаешь селект  только по таблице user_film_likes. Что если юзер не поставил ни одного лайка? По идее в таком случае user_id не будет присутствовать с таблице user_film_likes

2023-05-29 09:21 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/inMemory/InMemoryFilmStorage.java
> +        return new HashMap<>();
Здесь в остальных методах выбрасывается исключение, вероятно стоит сделать аналогичное поведение для новых методов, чтобы не запутаться.

2023-05-29 09:21 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/inMemory/InMemoryFilmStorage.java
> +        return new ArrayList<>();
С этим методом аналогично - лучше выбрасывать исключение для одинакового поведения.

2023-05-29 09:21 UTC, Yuri-Yamaltdinov commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:file:./db/sprint12
Путь отличается от ветки develop, надо выровнять с develop

2023-05-29 09:21 UTC, Yuri-Yamaltdinov commented on src/main/resources/application.properties
> +spring.datasource.password=password
Пароль отличается от ветки develop, надо выровнять с develop

2023-05-29 09:21 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/service/recommendations/RecommendationsService.java
> +    private Map<Long, Set<Long>> usersLikedFilmsIds;
Тот же вопрос - не следует ли сделать указать final?

2023-05-30 17:12 UTC, Vexvl commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +    private final JdbcTemplate jdbcTemplateNotNamedParameter;
Просто это другая реализация запросов к бд

2023-05-30 17:25 UTC, Vexvl commented on src/main/java/ru/yandex/practicum/filmorate/service/recommendations/RecommendationsService.java
> +    private Map<Long, Set<Long>> usersLikedFilmsIds;
Но мапа же каждый раз меняется, подскажите, почему она должна быть final

2023-05-30 21:07 UTC, Vexvl commented on src/main/java/ru/yandex/practicum/filmorate/service/recommendations/RecommendationsService.java
> +    }
что-то я забуксовал, посмотрите, пожалуйста, что может быть ошибочно в методе
    public Map<Long, Set<Long>> fillInUserLikes(long userId) {
        String sqlQuery = "WITH " +
                "commonFilms AS (" +
                "   SELECT film_id " +
                "   FROM USER_FILM_LIKES " +
                "   WHERE user_id = :userId" +
                "), " +
                "similarUsers AS (" +
                "   SELECT user_id " +
                "   FROM USER_FILM_LIKES " +
                "   WHERE film_id IN (SELECT film_id FROM commonFilms)" +
                ") " +
                "SELECT user_id, film_id " +
                "FROM USER_FILM_LIKES " +
                "WHERE user_id IN (SELECT user_id FROM similarUsers) " +
                "  AND film_id NOT IN (SELECT film_id FROM commonFilms)";

        Map<Long, Set<Long>> usersLikedFilmsIds = new HashMap<>();

        SqlParameterSource parameters = new MapSqlParameterSource("userId", userId);
        SqlRowSet rowSet = jdbcTemplate.queryForRowSet(sqlQuery, parameters);

        while (rowSet.next()) {
            long user = rowSet.getLong("USER_ID");
            long filmId = rowSet.getLong("FILM_ID");

            Set<Long> filmIds = usersLikedFilmsIds.get(user);
            if (filmIds == null) {
                filmIds = new HashSet<>();
                usersLikedFilmsIds.put(user, filmIds);
            }
            filmIds.add(filmId);
        }
        return usersLikedFilmsIds;
    }

2023-05-31 05:48 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/service/recommendations/RecommendationsService.java
> +    }
это я немного затупил - в финальной части запроса достаточно только фильмы вытаскивать - по сути это и есть рекомендации - их можно собрать в List / Set просто:
"SELECT film_id " +
"FROM USER_FILM_LIKES " +
"WHERE user_id IN (SELECT user_id FROM similarUsers) " +
" AND film_id NOT IN (SELECT film_id FROM commonFilms)";

2023-05-31 07:09 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/service/recommendations/RecommendationsService.java
> +    private Map<Long, Set<Long>> usersLikedFilmsIds;
Т.к. мапа является объектом, то работа с ней осуществляется через ссылку на объект. Если указываешь final, то при любом обращении к переменной с именем мапы ссылка всегда будет на один и тот же объект. Если же не final, то может возникнуть ситуация, когда в памяти будет создана новая мапа и ссылка поменяется на новую мапу.

2023-05-31 11:45 UTC, c0m14 approved these changes

2023-05-31 16:10 UTC, Yuri-Yamaltdinov approved these changes

2023-05-31 17:16 UTC, merged