Group Project Pull Request
c0m14/java-filmorate pull request #18
Opened 2023-05-31 17:51 UTC by HoneyVanity

2023-06-01 21:18 UTC, NikolaiDem requested changes

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/DirectorController.java
> +            @PathVariable("id") @Min(1) Integer directorId
Аннотации валидации обрабатываются через @Validated. @Valid здесь лишнее

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/DirectorController.java
> +    public Director add(@Valid @RequestBody Director director) throws InvalidFieldsException {
throws с непроверяемыми исключениями лишний

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/DirectorController.java
> +    public Director update(@Valid @RequestBody Director director) throws InvalidFieldsException {
throws с непроверяемыми исключениями лишний

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/DirectorController.java
> +            @PathVariable("id") @Min(1) Integer directorId
Аннотации валидации обрабатываются через @validated. @Valid здесь лишнее

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +            log.debug("With genreId {}, genreId");
genreId предполагался за пределами строки

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +            @Valid
Аннотации валидации обрабатываются через @validated. @Valid здесь лишнее

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +            @Valid
Аннотации валидации обрабатываются через @validated. @Valid здесь лишнее

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +        if (by == null || by.isEmpty()) {
Логику по конструированию фильтра лучше вынести в отдельный класс, чтобы не смешивать логику маршрутизации с логикой поиска

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/filmReview/FilmReviewController.java
> +            @Valid
Аннотации валидации обрабатываются через @validated. @Valid здесь лишнее

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/user/UserController.java
> +            @Valid
Аннотации валидации обрабатываются через @validated. @Valid здесь лишнее

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/user/UserController.java
> +            @Valid
Аннотации валидации обрабатываются через @validated. @Valid здесь лишнее

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/exception/DirectorNotExistsException.java
> +public class DirectorNotExistsException extends RuntimeException {
Множество исключений вида CustomObjectNotExistsException не несет большой ценности, потому что в хэндлере для каждого типа все равно захардкожен тип объекта. Тогда логичнее сделать одно общее исключение ...NotExistsException и туда передавать тип поля, который затем отдавать хендлеру

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/CataloguedFilm.java
> +        film.getDirectors().forEach(director -> filmDirectors.add(director.getName().toLowerCase()));
Хорошей практикой считается использовать в стримах неизменяемые объекты. Альтернатива - получить список имен режиссеров  и добавить (addAll) их в filmDirectors.

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/feed/FeedStorage.java
> +    void addEvent(Long userId, Long entityId, EventType eventType, OperationType operationType);
Почему не передать доменный объект Feed вместо набора параметров ?)

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/feed/h2/FeedRepository.java
> +        } catch (FeedStorageEmptyException e) {
Точно ли здесь может быть брошено FeedStorageEmptyException  ?

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/DirectorDaoImpl.java
> +            jdbcTemplate.update(sqlQuery, filmId, directorId);
Для множественного обновления лучше использовать jdbcTemplate.batchUpdate(String sql, final BatchPreparedStatementSetter pss), чтобы сделать это одним запросом.

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/DirectorDaoImpl.java
> +                "(SELECT director_id " +
Для чего вложенный селект? В where сразу фильтр по фильмам можно включить?

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/DirectorDaoImpl.java
> +        List<Map<Long, Director>> filmIdWithDirectorList = namedParameterJdbcTemplate.query(sqlQuery, namedParams, ((rs, rowNum) -> Collections.singletonMap(
Чтобы не создавать список мап, можно использовать query(...) с RowCallbackHandler, и добавлять режиссеров в фильм в процессе итерации по ResultSet-у

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
>      public void giveLikeFromUserToFilm(Long filmId, Long userId) {
Метод выглядит лишним в этом репозитории, больше относится к сервису

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
>      public boolean removeUserLikeFromFilm(Long filmId, Long userId) {
Метод выглядит лишним в этом репозитории, больше относится к сервису

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +            Long filmId = rowSet.getLong("FILM_ID");
long filmId

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +                Set<Long> filmIds = usersLikedFilmsIds.get(userId);
Set<Long> filmIds = usersLikedFilmsIds.computeIfAbsent(userId, k -> new HashSet<>());

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/recommendations/RecommendationsService.java
> +        Map<Long, Set<Long>> usersLikedFilmsIds = filmStorage.fillInUserLikes();
Нужно ли возвращать всех пользователей в память, можно ли сделать поиск пересечений на уровне БД?

2023-06-01 21:18 UTC, NikolaiDem commented on src/main/resources/schema.sql
>  DROP TABLE IF EXISTS USERS CASCADE;
Удалять таблицы не нужно

2023-06-02 07:35 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/DirectorController.java
> +            @PathVariable("id") @Min(1) Integer directorId
Спасибо! поправил везде)

2023-06-02 08:26 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/exception/DirectorNotExistsException.java
> +public class DirectorNotExistsException extends RuntimeException {
Спасибо! сделал рефакторинг

2023-06-02 14:02 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/DirectorDaoImpl.java
> +            jdbcTemplate.update(sqlQuery, filmId, directorId);
Скорректировано в коммите [refactor: using jdbcTemplate.batchUpdate for multiple calls in DirectorDaoImpl]

2023-06-02 14:03 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/DirectorDaoImpl.java
> +                "(SELECT director_id " +
Скорректировано в коммите [fix: removed redundant nested select in DirectorDaoImpl]

2023-06-02 18:04 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/DirectorDaoImpl.java
> +        List<Map<Long, Director>> filmIdWithDirectorList = namedParameterJdbcTemplate.query(sqlQuery, namedParams, ((rs, rowNum) -> Collections.singletonMap(
Скорректировано в коммите [refactor: map usage replaced by query with RowCallbackHandler]

2023-06-02 18:10 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/DirectorController.java
> +    public Director add(@Valid @RequestBody Director director) throws InvalidFieldsException {
Исправлено

2023-06-02 18:10 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/DirectorController.java
> +    public Director update(@Valid @RequestBody Director director) throws InvalidFieldsException {
Исправлено

2023-06-02 19:26 UTC, SychMaf commented on src/main/java/ru/yandex/practicum/filmorate/repository/feed/h2/FeedRepository.java
> +        } catch (FeedStorageEmptyException e) {
Скорректировано в коммите [refactor feed repository, create feed and remove not used exception]

2023-06-02 19:26 UTC, SychMaf commented on src/main/java/ru/yandex/practicum/filmorate/repository/feed/FeedStorage.java
> +    void addEvent(Long userId, Long entityId, EventType eventType, OperationType operationType);
Скорректировано в коммите [refactor feed repository, create feed and remove not used exception]

2023-06-02 19:52 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +            log.debug("With genreId {}, genreId");
Неловко вышло)
Поправили

2023-06-02 19:52 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +        if (by == null || by.isEmpty()) {
Перенес валидацию и конструирование параметра by в фильмсервис

2023-06-02 19:56 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/model/CataloguedFilm.java
> +        film.getDirectors().forEach(director -> filmDirectors.add(director.getName().toLowerCase()));
Благодарю, буду знать!
Поправил

2023-06-02 20:54 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
>      public void giveLikeFromUserToFilm(Long filmId, Long userId) {
Метод переехал в FilmService

2023-06-02 20:54 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
>      public boolean removeUserLikeFromFilm(Long filmId, Long userId) {
Метод переехал в FilmService

2023-06-04 14:04 UTC, NikolaiDem requested changes

2023-06-04 14:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +        return filmService.searchFilms(query.toLowerCase(), by);
Если by все равно передается в сервис, то лучше передать сырой by в searchFilms(...), чтобы сервис внутри себя сам выполнил validateAndSetParameterByForSearch(...). Или сделать validateAndSetParameterByForSearch(...) в отдельном классе от FilmService, тогда можно оставить его в вызов в контроллере

2023-06-04 14:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/GenreController.java
> -@Validated
Для аннотаций валидации (например, @Min) @Validated нужен

2023-06-04 14:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/MpaController.java
> -@Validated
Для аннотаций валидации (например, @Min) @Validated нужен

2023-06-04 14:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/exception/InvalidDirectorFieldsException.java
> +public class InvalidDirectorFieldsException extends InvalidFieldsException {
Не используется

2023-06-04 14:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/exception/InvalidFilmReviewFieldsException.java
> +public class InvalidFilmReviewFieldsException extends InvalidFieldsException {
Какой профит от создания наследника InvalidFieldsException ?

2023-06-04 14:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/CataloguedFilm.java
> +                .stream()
Чтоб совсем красиво, можно
.stream()
                .map(Director::getName)
                .map(String::toLowerCase)
                .collect(Collectors.toList()));

2023-06-04 14:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +        directorDao.removeDirectorsFromFilm(film.getId());
Код дублируется с 67-75 строками, лучше вынести в отдельный метод

2023-06-04 14:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +            if (rowSet.wasNull()) {
Почему может быть null, и нужен ли left join?

2023-06-04 14:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +        StringJoiner filmIdsString = new StringJoiner(",");
Или так:
        String filmIdsString = filmIds.stream()
                .map(String::valueOf)
                .collect(Collectors.joining(","));

2023-06-04 14:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +                "LEFT JOIN directors AS d ON fd.director_id = d.director_id " +
join к directors здесь лишний

2023-06-04 14:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/GenreService.java
> +        if (id <= 0) {
В контроллере уже есть валидация @Min

2023-06-04 14:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/RatingMpaService.java
> +        if (mapId <= 0) {
В контроллере уже есть валидация @min

2023-06-04 15:42 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/GenreController.java
> -@Validated
Убрал валидацию **min** и перенес логику проверки в сервис, чтобы возвращать 404 ошибку, если genre / mpa rating не найдены при передаче некорректного id

2023-06-04 16:14 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/exception/InvalidDirectorFieldsException.java
> +public class InvalidDirectorFieldsException extends InvalidFieldsException {
Спасибо, убрал

2023-06-04 16:15 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/exception/InvalidFilmReviewFieldsException.java
> +public class InvalidFilmReviewFieldsException extends InvalidFieldsException {
Да, спасибо - убрал лишние исключения, оставил только общее с передачей поля названия класса для расшифровки

2023-06-04 16:38 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +        return filmService.searchFilms(query.toLowerCase(), by);
Поправил. by теперь передается в сервис сырым

2023-06-04 16:38 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/model/CataloguedFilm.java
> +                .stream()
Благодарю! Так и правда выглядит красивее

2023-06-04 20:53 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +        directorDao.removeDirectorsFromFilm(film.getId());
Спасибо, создал приватный метод

2023-06-04 20:54 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +                "LEFT JOIN directors AS d ON fd.director_id = d.director_id " +
Спасибо, убрал лишний JOIN

2023-06-05 09:35 UTC, NikolaiDem approved these changes

2023-06-05 09:35 UTC, NikolaiDem approved these changes

2023-06-06 06:04 UTC, merged