Controllers films users
c0m14/java-filmorate pull request #2
Opened 2023-03-19 19:56 UTC by c0m14

2023-03-20 20:09 UTC, ohelly requested changes
Привет! Отличная работа, все работает корректно. У меня нет замечаний, но есть несколько рекомендаций, на которые стоит обратить внимание. Их выполнять не обязательно, в таком случае можешь просто прислать этот же вариант работы снова на проверку и я ее приму.

2023-03-20 20:09 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmNotExistException.java
> +package ru.yandex.practicum.filmorate.exceptions;
Рекомендация: Обычно пакеты в java именуют в единственном числе. В данном случае тоже можно переименовать.

2023-03-20 20:09 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(
Рекомендация: Данный конструктор можно заменить с помощью аннотации ломбока ``@AllArgsConstructor``. Также можно выпилить аннотации ``@JsonProperty``, так как название полей идентично тем, что заданы в аннотациях.

2023-03-20 20:09 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Рекомендация: Будет лучше, если идентификатор будет иметь типа класса обертки(Long, Integer) вместо примитивного int. Это связано с тем, что примитив по дефолту имеет значение 0 даже если его не задать, в отличии от оберток, которые могут иметь значение null. Таким образом мы можем отслеживать, было ли задано значение или нет.

2023-03-20 20:09 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
Рекомендация: Для полей типа String не обязательно ставить две аннотации ``@NotNull`` и ``@NotBlank``. Достаточно оставить только вторую, так как в ней уже есть проверка на null.

2023-03-20 20:09 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
Здесь также можно применить все рекомендации из класса Film.

2023-03-20 20:09 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!films.keySet().contains(film.getId())) {
Рекомендация: Для проверки существующего фильма необязательно доставать keySet, у мапы есть метод containsKey

2023-03-20 20:09 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/RequestType.java
> +package ru.yandex.practicum.filmorate.controller;
Рекомендация: Данную модель лучше вынести в пакет модель, так как он не является контроллером.

2023-03-20 20:09 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Рекомендация: Также здесь можно применить некоторые рекомендации из класса FilmController.

2023-03-21 06:03 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(
Спасибо! конструктор заменил аннотацией, но @JsonProperty не получилось убрать - при на тестах выбрасывает исключение при попытке сгенерить объект из post запроса (я как раз из-за него нагуглил решение через аннотацию):

org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class ru.yandex.practicum.filmorate.model.User]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `ru.yandex.practicum.filmorate.model.User` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 2]

2023-03-21 06:27 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
о, спасибо! как раз смущало приведение к 0 по умолчанию, не подумал про обертки)

2023-03-21 16:33 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(
Судя по ексепшену ему не хватает дефолтного(пустого) конструктора. Можешь попробовать добавить еще аннотацию ``@NoArgsConstructor`` и должно взлететь

2023-03-21 16:36 UTC, ohelly approved these changes
Привет! Все супер, прекрасная работа! Можно двигаться дальше, работу принимаю!
Также оставил коммент под твоим ответом про ``@JsonProperty`` в прошлой рекомендации

2023-03-21 17:19 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(
Спасибо, все получилось! :)

2023-03-21 17:23 UTC, merged