Add database
c0m14/java-filmorate pull request #6
Opened 2023-05-02 19:35 UTC by c0m14

2023-05-03 19:55 UTC, ohelly requested changes
Привет! Отличная работа, здорово, что используются транзакции, да и в целом все выглядит очень хорошо. Есть одно небольшое замечание, которое необходимо исправить. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.
В случае возникновения вопросов можно обращаться ко мне в пачку.

2023-05-03 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/h2/UserRepository.java
> +            return Collections.EMPTY_LIST;
Рекомендация: Можно использовать фичи 11 джавы: return List.of();

2023-05-03 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +    @Transactional
Отлично, что используется аннотация транзакции!

2023-05-03 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +                    .forEach(genreId -> filmGenreDao.setGenreToFilm(filmId, genreId));
Рекомендация: Можно переделать метод вставки жанров для фильмов одним запросом. Сейчас происходит столько запросов, сколько жанров и пришло.

2023-05-03 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +        String sqlQuery = "SELECT film_id, film_name, description, release_date, duration, mpa_rating_id " +
Рекомендация: Рейтинг можно доставать в рамках этого же запроса с использованием джоина, чтобы не делать дополнительный запрос. Так мы сможем уменьшить нагрузку на БД, что явялется хорошей практикой.

2023-05-03 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +        films.forEach(this::fetchAdditionalParams);
Необходимо исправить: Внутри метода ``fetchAdditionalParams`` есть метод получения жанров для фильма. И все работает хорошо, когда мы достаем один фильм, но когда мы достаем несколько фильмов, как в данном случае, то этот метод вызывается каждый раз, для каждого фильма из-за forEach. То есть на N фильмов делается N запросов для получения жанров. Это необходимо исправить и доставать жанры одним запросом независимо от количества фильмов. Для этого поможет запрос с оператором IN и HashMap.
P.S. Данную проблему необходимо обязательно исправить только для жанров, для лайков и рейтинга - рекомендация, но для рейтинга и так исправится если в запрос добавить JOIN.

2023-05-03 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +        films.forEach(this::fetchAdditionalParams);
Необходимо исправить: Аналогичная проблема с множественными запросами для жанров.

2023-05-03 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +    public RatingMPA getMpaById(int mapId) {
Рекомендация: Для всех методов связанных с MPA и жанрами можно создать соответствующие классы сервисы и вынести их туда, чтобы не не мешать логику в данном классе.

2023-05-03 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +        String sqlQuery = "SELECT film_id, film_name, description, release_date, duration, mpa_rating_id " +
Рекомендация: Также можно добавить джоин на таблицу с рейтингом и преобразовывать его в объект RatingMPA в методе ``mapRowToFilm``

2023-05-04 08:17 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +                    .forEach(genreId -> filmGenreDao.setGenreToFilm(filmId, genreId));
Спасибо! :) меня тоже мучала мысль, что как-то наверно дороговато так много в БД ходить)

2023-05-05 10:27 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +        films.forEach(this::fetchAdditionalParams);
Спасибо!

2023-05-05 20:49 UTC, ohelly approved these changes
Привет! Теперь все отлично, исправлены все замечания. Работу принимаю, можно двигаться дальше. Удачи в дальнейшем обучении!

2023-05-05 20:49 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +    private void fetchAdditionalParams(Film film) {
Рекомендация: Данный метод в целом можно удалить и использовать тот, который ниже, который принимает на вход список. Просто когда он будет использоваться для одного фильма можно сделать вот так: ``fetchAdditionalParamsToFilmsList(List.of(film));``

2023-05-05 21:06 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/h2/FilmRepository.java
> +    private void fetchAdditionalParams(Film film) {
спасибо тебе большое за помощь и советы и такие полные и понятные комментарии!🙂

2023-05-07 11:09 UTC, merged