Add reviews
c0m14/java-filmorate pull request #8
Opened 2023-05-24 19:10 UTC by c0m14

2023-05-26 21:19 UTC, HoneyVanity approved these changes
Никита, посмотрела весь код, постаралась вникнуть. Непривычно просматривать код не в среде IDEA, но явных противоречий не увидела, по названиям вопросов нет.

2023-05-27 13:37 UTC, dimaAndriyanov requested changes
Все очень хорошо!
 Надо только разобраться с запросами к базе данных для получения рейтинга полезности отзывов.

2023-05-27 13:37 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/repository/filmReview/h2/FilmFilmReviewRepository.java
> +        String sqlQuery = "SELECT r.review_id, r.user_id, r.film_id, r.content, r.is_positive, " +
Такой запрос в общем случае не сработает. Когда ты джойнишь таблицы таким образом, у тебя получается много строк с повторениями и без пустых ячеек. Таким образом count(...) - count(...) всегда будет возвращать 0, если у ревью есть хотя бы одна положительная оценка и одна отрицательная.
Пример у ревью р1 есть два лайка от юзеров ю2 и ю3 и один дизлайк от юзера ю4
Получится следующий результат:
р1, ю2, ю4
р1, ю3, ю4
и  count(likes.user_id) - count(dislikes.user_id) = 2 - 2 = 0
следует учитывать только уникальные значения для поля user_id

2023-05-27 13:37 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/repository/filmReview/h2/FilmFilmReviewRepository.java
> +                "GROUP BY r.review_id ";
в этом запросе r.review_id всегда равняется :reviewId, группировать по этому полю излишне.

2023-05-27 13:37 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/repository/filmReview/h2/FilmFilmReviewRepository.java
> +        String sqlQuery = "SELECT COUNT(likes.user_id) - COUNT(dislikes.user_id) " +
В этом запросе аналогичная проблема, что и выше.

2023-05-27 13:37 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/repository/filmReview/h2/FilmFilmReviewRepository.java
> +                "GROUP BY likes.review_id, dislikes.review_id";
Когда ты ведешь подсчет по всем записям в таблице, группировать эти записи необязательно.
Например, когда у тебя в таблице только одно ревью и ты хочешь посчитать количество его лайков, группировать данные ненужно.
А если у тебя в таблице присутствуют разные ревью и ты хочешь посчитать количество лайков для каждого отдельного ревью, то тут уже нужно применять группировку по review_id.

2023-05-27 20:16 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/repository/filmReview/h2/FilmFilmReviewRepository.java
> +        String sqlQuery = "SELECT r.review_id, r.user_id, r.film_id, r.content, r.is_positive, " +
ооо. спасибо большое! я бы в жизни это просто вот так при чтении кода не заметил и даже в тестах пропустил этот момент) добавил проверку на уникальность

2023-05-27 20:18 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/repository/filmReview/h2/FilmFilmReviewRepository.java
> +                "GROUP BY r.review_id ";
в DBeaver действительно почему-то работает без группировки, но в идее валятся исключения БД, что для группирующей функции нужен Group by, поэтому оставил

2023-05-27 20:18 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/repository/filmReview/h2/FilmFilmReviewRepository.java
> +        String sqlQuery = "SELECT COUNT(likes.user_id) - COUNT(dislikes.user_id) " +
поправил, спасибо!

2023-05-27 20:19 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/repository/filmReview/h2/FilmFilmReviewRepository.java
> +                "GROUP BY likes.review_id, dislikes.review_id";
да, спасибо большое! тут без группировки отлично срабатывает

2023-05-27 20:29 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/repository/filmReview/h2/FilmFilmReviewRepository.java
> +        String sqlQuery = "SELECT r.review_id, r.user_id, r.film_id, r.content, r.is_positive, " +
ну я тоже не при чтении кода, это обнаружил) мне показалась группировка лишней. и перед тем, как написать комментарий, решил проверить: а можно ли без нее, и там уже обнаружил, что запрос не совсем корректен

2023-05-27 20:30 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/repository/filmReview/h2/FilmFilmReviewRepository.java
> +                "GROUP BY r.review_id ";
интересно)

2023-05-27 20:41 UTC, dimaAndriyanov commented on src/main/java/ru/yandex/practicum/filmorate/repository/filmReview/h2/FilmFilmReviewRepository.java
> +        String sqlQuery = "SELECT COUNT(likes.user_id) - COUNT(dislikes.user_id) " +
здесь все оказалось немного сложнее: тут тебе нужен не иннер джоин, а фулл аутер джоин. потому что если, например, у тебя у отзыва есть только лайки, а дизлайков нет, то иннер джоин даст пустую таблицу, и подсчитывать особо будет нечего. в приложении это вылезет, когда ты, например, обновишь отзыв, у которого уже есть два лайка и нет дизлайков, а в ответе на запрос вернется отзыв с нулевым рейтингом полезности
но главная проблема, насколько я понимаю, в том, что в н2 нет фулл аутер джоина(
можно использовать, например, такой запрос
SELECT (
    SELECT COUNT(USER_ID)
    FROM USER_REVIEW_LIKES
    WHERE REVIEW_ID = :reviewId
) - (
    SELECT COUNT(USER_ID)
    FROM USER_REVIEW_LIKES
    WHERE REVIEW_ID = :reviewId
)

2023-05-28 13:02 UTC, c0m14 commented on src/main/java/ru/yandex/practicum/filmorate/repository/filmReview/h2/FilmFilmReviewRepository.java
> +        String sqlQuery = "SELECT COUNT(likes.user_id) - COUNT(dislikes.user_id) " +
Cпасибо большое, что нашел еще один баг и даже подсказал как поправить! поправил и добавил еще тест кейсы небольшие на эти случаи

2023-05-28 13:06 UTC, dimaAndriyanov approved these changes

2023-05-28 16:40 UTC, merged