feat: delete users & films
c0m14/java-filmorate pull request #9
Opened 2023-05-26 22:12 UTC by HoneyVanity

2023-05-28 09:59 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/FilmStorage.java
> +    void removeFilmById(Long filmId);
чтобы прошли PR тесты надо добавить заглушку этого метода в InMemoryFilmStorage

2023-05-28 10:00 UTC, Yuri-Yamaltdinov commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserStorage.java
> +    void removeUserById(Long userId);
чтобы прошли PR тесты надо добавить заглушку этого метода в InMemoryUserStorage

2023-05-28 16:35 UTC, c0m14 requested changes
Привет! На мой взгляд все отлично! :)
Только сделать заглушки для InMemory классов (там есть уже пример в самом коде если что) и уточнить по логике каскадного удаления :)

2023-05-28 16:35 UTC, c0m14 commented on src/main/resources/schema.sql
> +                         USER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ON DELETE CASCADE,
Могу ошибаться, но кажется ON DELETE CASCADE нужно прописать во всех смежных таблицах в которых должна быть удалена запись при удалении пользователя

Например у меня в отзывах есть смежная таблица для лайков - и я там в свойствах FK описываю, что нужно удалить запись:

CREATE TABLE USER_REVIEW_LIKES (
                                   USER_ID INTEGER,
                                   REVIEW_ID INTEGER,
                                   PRIMARY KEY (USER_ID, REVIEW_ID),
                                   CONSTRAINT fk__user_review_likes__users FOREIGN KEY (USER_ID)
                                       REFERENCES USERS (USER_ID),
                                   CONSTRAINT fk__user_review_likes__review FOREIGN KEY (REVIEW_ID)
                                        REFERENCES REVIEW (REVIEW_ID)
                                   ON DELETE CASCADE
);

Твой вариант не смог проверить - у меня DBeaver ругается как раз на эти строчки при попытке создать таблицы :)

2023-05-28 16:35 UTC, c0m14 commented on src/main/resources/schema.sql
> +                        FILM_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ON DELETE CASCADE,
Тут наверное тоже нужно поправить и перенести в нужные таблицы записи
В своих я тоже сразу добавлю :)

2023-05-29 15:46 UTC, Yuri-Yamaltdinov approved these changes
С моей точки зрения всё ОК.

2023-05-29 19:17 UTC, c0m14 approved these changes
Cпасибо! теперь все отлично :)

2023-05-30 01:24 UTC, merged